name: generate-sbom

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sbom:
    name: sbom
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Generate SBOM
        uses: anchore/sbom-action@57aae528053a48a3f6235f2d9461b05fbcb7366d
        with:
          path: .

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: sbom
          path: |
            *.spdx.json
            *.syft.json
